name: build-and-deploy
on:
  push: 
    branches:
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pnpm
        run: curl -fsSL https://get.pnpm.io/install.sh | sh -
      - name: Build Files
        run: |
          pnpm i
          pnpm build
      - name: Fix permissions
        run: |
          chmod -c -R +rX "dist/" | while read line; do
            echo "Invalid file permissions fixed: $line"
          done
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "dist/"
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
